CREATE TABLE "PRODUCT"
(
   ID bigint PRIMARY KEY NOT NULL,
   CREATED timestamp NOT NULL,
   UPDATED timestamp NOT NULL,
   VERSION bigint,
   NAME varchar(255),
   DEFAULTUNIT_ID bigint,
   TYPE_ID bigint
)
;
CREATE TABLE "PRODUCTTYPE"
(
   ID bigint PRIMARY KEY NOT NULL,
   CREATED timestamp NOT NULL,
   UPDATED timestamp NOT NULL,
   VERSION bigint,
   NAME varchar(255)
)
;
CREATE TABLE "SHOPPINGLIST"
(
   ID bigint PRIMARY KEY NOT NULL,
   CREATED timestamp NOT NULL,
   UPDATED timestamp NOT NULL,
   VERSION bigint,
   NAME varchar(255)
)
;
CREATE TABLE "SHOPPINGLISTITEM"
(
   ID bigint PRIMARY KEY NOT NULL,
   CREATED timestamp NOT NULL,
   UPDATED timestamp NOT NULL,
   VERSION bigint,
   QUANTITY varchar(255),
   PRODUCT_ID bigint,
   SHOPPINGLIST_ID bigint,
   UNIT_ID bigint
)
;
CREATE TABLE "UNIT"
(
   ID bigint PRIMARY KEY NOT NULL,
   CREATED timestamp NOT NULL,
   UPDATED timestamp NOT NULL,
   VERSION bigint,
   NAME varchar(255)
)
;
CREATE TABLE "HIBERNATE_SEQUENCES"
(
   SEQUENCE_NAME varchar(255),
   SEQUENCE_NEXT_HI_VALUE int
)
;
ALTER TABLE "PRODUCT"
ADD CONSTRAINT FK_PRODUCT_TYPE_ID
FOREIGN KEY (TYPE_ID)
REFERENCES "PRODUCTTYPE"(ID)
;
ALTER TABLE "PRODUCT"
ADD CONSTRAINT FK_PRODUCT_DEFAULTUNIT_ID
FOREIGN KEY (DEFAULTUNIT_ID)
REFERENCES "UNIT"(ID)
;
CREATE INDEX SQL_PRODUCT_DEFAULTUNIT_ID ON "PRODUCT"(DEFAULTUNIT_ID)
;
CREATE UNIQUE INDEX SQL_PRODUCT_ID ON "PRODUCT"(ID)
;
CREATE INDEX SQL_PRODUCT_TYPE_ID ON "PRODUCT"(TYPE_ID)
;
CREATE UNIQUE INDEX UK_PRODUCT_NAME ON "PRODUCT"(NAME)
;
CREATE UNIQUE INDEX UK_PRODUCTTYPE_NAME ON "PRODUCTTYPE"(NAME)
;
CREATE UNIQUE INDEX SQL_PRODUCTTYPE_ID ON "PRODUCTTYPE"(ID)
;
CREATE UNIQUE INDEX SQL_SHOPPINGLIST_ID ON "SHOPPINGLIST"(ID)
;
CREATE UNIQUE INDEX UK_SHOPPINGLIST_NAME ON "SHOPPINGLIST"(NAME)
;
ALTER TABLE "SHOPPINGLISTITEM"
ADD CONSTRAINT FK_SHOPPINGLISTITEM_PRODUCT_ID
FOREIGN KEY (PRODUCT_ID)
REFERENCES "PRODUCT"(ID)
;
ALTER TABLE "SHOPPINGLISTITEM"
ADD CONSTRAINT FK_SHOPPINGLISTITEM_UNIT_ID
FOREIGN KEY (UNIT_ID)
REFERENCES "UNIT"(ID)
;
ALTER TABLE "SHOPPINGLISTITEM"
ADD CONSTRAINT FK_SHOPPINGLISTITEM_SHOPPINGLIST_ID
FOREIGN KEY (SHOPPINGLIST_ID)
REFERENCES "SHOPPINGLIST"(ID)
;
CREATE INDEX SQL_SHOPPINGLISTITEM_SHOPPINGLIST_ID ON "SHOPPINGLISTITEM"(SHOPPINGLIST_ID)
;
CREATE UNIQUE INDEX SQL_SHOPPINGLISTITEM_ID ON "SHOPPINGLISTITEM"(ID)
;
CREATE INDEX SQL_SHOPPINGLISTITEM_PRODUCT_ID ON "SHOPPINGLISTITEM"(PRODUCT_ID)
;
CREATE INDEX SQL_SHOPPINGLISTITEM_UNIT_ID ON "SHOPPINGLISTITEM"(UNIT_ID)
;
CREATE UNIQUE INDEX UK_UNIT_NAME ON "UNIT"(NAME)
;
CREATE UNIQUE INDEX SQL_UNIT_ID ON "UNIT"(ID)
;
